### ISSUE TITLE
Poner los botones de Ver, Editar y Eliminar como link

### ISSUE THREAD

**Issue by carlirouscust** [AlainaG01/RegistroTecnicos#12]
https://github.com/AlainaG01/RegistroTecnicos/blob/b82e5f5a3c68570d29fe323e9bf89ffac4fdc623/RegistroTecnicos/Components/Pages/PrioridadesPages/IndexPrioridades.razor#L67

Ejemplo:
![image](https://github.com/user-attachments/assets/7318ad07-1693-49ba-97c9-ab1596b1f3e9)

Explicación: El @Priodidades, es el nombre de la variable donde se esta guardando la listaPrioridades, ya directamente de ahí se puede obtener el PrioridadesID sin necesidad de utilizar un método

**Comment by AlainaG01** [comment]
Gracia!
